INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('AJAIB','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('BAHANA','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('BCA SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('BNI SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('CIMB SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('DANAREKSA SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('DHANAWIBAWA','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('ERDIKHA SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('FAC SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('HP FINANCIALS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('INDOPREMIER','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('INDOSURYA BERSINAR SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('INTI TELADAN SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('JASA UTAMA CAPITAL','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('KIWOOM SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('KRESNA SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('MANDIRI SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('MAYBANK SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('MEGACAPITAL SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('MINNA PADI INVESTAMA SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('MIRAE ASEET SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('MNC SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('NH KORINDO SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('NISP SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('OCBC SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('OSO SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('PACIFIC 2000 SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('RELIANCE SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('RHB SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('SAMUEL SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('SINARMAS SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('SUCOR SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('TRIMEGAH SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('UNIVERSAL BROKER INDONESIA SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('UOB SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('VALBURY SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('VICTORIA SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('WANTEG SEKURITAS','','',1);
INSERT INTO `sekuritas`(`Nama`, `Inisial`, `Logo`, `Show_Status`) VALUES ('YUANTA SEKURITAS','','',1);